steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Containerfile",
        "-t",
        "us-docker.pkg.dev/quick-guru-393523/algo-trading:$COMMIT_SHA",
        ".",
      ]
images:
  - "us-docker.pkg.dev/quick-guru-393523/algo-trading:$COMMIT_SHA"
